language: scala
jdk:
- oraclejdk7
env:
  global:
  - secure: D67lbC+UaIrlmL9KC7eegzw5i0xeRI+L99iUenR5krhfCOZtKX1VcJtR4fl+YXYQ6QJwJbAx1N5RkjshZcR/v9iD8++9E8KkhixF3n1fHmeQa61AQ1GpQTPv2PiEIxvnf0qJNfjsc14Kcp5lgXd9ZtDSxLVrjsR5mJO2JyVkHqk=
before_script:
- echo "TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG, TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST, TRAVIS_BRANCH=$TRAVIS_BRANCH"
script: scripts/ci-build
after_success:
- scripts/coveralls
- scripts/update-site-from-travis
notifications:
  email: false
