sudo: false
language: scala
scala:
  - 2.11.12
  - 2.12.6
jdk:
  - oraclejdk8
env:
  global:
  - ENCRYPTION_ID: "9eb27d59440e"
before_script:
  - echo "TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG, TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST, TRAVIS_BRANCH=$TRAVIS_BRANCH"
cache:
  directories:
    # caching scala stuff based on
    # http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html#%28Experimental%29+Reusing+Ivy+cache
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
script:
  - scripts/ci-build
  # cleanup travis trick from
  # http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html#%28Experimental%29+Reusing+Ivy+cache
  - find $HOME/.sbt -name "*.lock" -delete
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
after_success:
  - scripts/api-doc
  - scripts/coveralls
notifications:
  email: false
